package com.mgaetan89.showsrage.fragment;

import com.google.gson.Gson;
import com.mgaetan89.showsrage.model.Show;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.Arrays;
import java.util.Collection;

import static org.assertj.core.api.Assertions.assertThat;

@RunWith(Parameterized.class)
public class ShowsSectionFragment_FilterReceiver_MatchTest {
	@Parameterized.Parameter(1)
	public int filterMode;

	@Parameterized.Parameter(2)
	public int filterStatus;

	@Parameterized.Parameter(3)
	public boolean match;

	@Parameterized.Parameter(0)
	public Show show;

	@Test
	public void match() {
		assertThat(ShowsSectionFragment.FilterReceiver.match(this.show, this.filterMode, this.filterStatus)).isEqualTo(this.match);
	}

	@Parameterized.Parameters(name = "{index} - mode: {1}, status: {2}, match: {3}")
	public static Collection<Object[]> data() {
		Gson gson = new Gson();

		return Arrays.asList(new Object[][]{
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{null, 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{null, 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{null, 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{null, 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{null, ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{null, 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ALL, true},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ALL, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_CONTINUING, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_ENDED, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), 3, ShowsFragment.FILTER_STATUS_UNKNOWN, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_ACTIVE, 4, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_BOTH, 4, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFragment.FILTER_PAUSED_ACTIVE_PAUSED, 4, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), 3, 4, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), 3, 4, false},
		});
	}
}
