package com.mgaetan89.showsrage.fragment;

import com.google.gson.Gson;
import com.mgaetan89.showsrage.model.Show;
import com.mgaetan89.showsrage.model.ShowsFilters;
import com.mgaetan89.showsrage.network.SickRageApi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.Arrays;
import java.util.Collection;

import static org.assertj.core.api.Assertions.assertThat;

// TODO Include search query
@RunWith(Parameterized.class)
public class ShowsSectionFragment_FilterReceiver_MatchTest {
	@Parameterized.Parameter(1)
	public ShowsFilters.State filterMode;

	@Parameterized.Parameter(2)
	public int filterStatus;

	@Parameterized.Parameter(3)
	public boolean match;

	@Parameterized.Parameter(0)
	public Show show;

	@Test
	public void match() {
		assertThat(ShowsSectionFragment.FilterReceiver.match(this.show, this.filterMode, this.filterStatus, "")).isEqualTo(this.match);
	}

	@Parameterized.Parameters(name = "{index} - mode: {1}, status: {2}, match: {3}")
	public static Collection<Object[]> data() {
		int all = ShowsFilters.Status.ALL.getStatus();
		int continuing = ShowsFilters.Status.CONTINUING.getStatus();
		int ended = ShowsFilters.Status.ENDED.getStatus();
		int unknown = ShowsFilters.Status.UNKNOWN.getStatus();
		Gson gson = SickRageApi.Companion.getGson();

		return Arrays.asList(new Object[][]{
				{null, ShowsFilters.State.ACTIVE, all, false},
				{null, ShowsFilters.State.ALL, all, false},
				{null, ShowsFilters.State.PAUSED, all, false},
				{null, ShowsFilters.State.ACTIVE, continuing, false},
				{null, ShowsFilters.State.ALL, continuing, false},
				{null, ShowsFilters.State.PAUSED, continuing, false},
				{null, ShowsFilters.State.ACTIVE, continuing | ended, false},
				{null, ShowsFilters.State.ALL, continuing | ended, false},
				{null, ShowsFilters.State.PAUSED, continuing | ended, false},
				{null, ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{null, ShowsFilters.State.ALL, continuing | ended | unknown, false},
				{null, ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{null, ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{null, ShowsFilters.State.ALL, continuing | unknown, false},
				{null, ShowsFilters.State.PAUSED, continuing | unknown, false},
				{null, ShowsFilters.State.ACTIVE, ended, false},
				{null, ShowsFilters.State.ALL, ended, false},
				{null, ShowsFilters.State.PAUSED, ended, false},
				{null, ShowsFilters.State.ACTIVE, ended | unknown, false},
				{null, ShowsFilters.State.ALL, ended | unknown, false},
				{null, ShowsFilters.State.PAUSED, ended | unknown, false},
				{null, ShowsFilters.State.ACTIVE, unknown, false},
				{null, ShowsFilters.State.ALL, unknown, false},
				{null, ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, all, true},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, all, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, all, true},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, all, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, all, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, continuing | unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, ended, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, ended, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, ended, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, ended, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, ended, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, ended, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, ended, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, ended, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, ended, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, ended | unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 0, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"continuing\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Continuing\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 0, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"ended\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Ended\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, unknown, true},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.ALL, unknown, true},
				{gson.fromJson("{paused: 0, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"unknown\"}", Show.class), ShowsFilters.State.PAUSED, unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, unknown, true},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.ALL, unknown, true},
				{gson.fromJson("{paused: 0, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Unknown\"}", Show.class), ShowsFilters.State.PAUSED, unknown, true},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 0, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"other status\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ACTIVE, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.ALL, unknown, false},
				{gson.fromJson("{paused: 0, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
				{gson.fromJson("{paused: 1, status: \"Other Status\"}", Show.class), ShowsFilters.State.PAUSED, unknown, false},
		});
	}
}
